// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniversitiesAPI.Infrastructure.Contracts.DBEntities
{
    public partial class UniversityPage
    {
        public UniversityPage()
        {
            University = new HashSet<University>();
        }

        [Key]
        public int Id { get; set; }
        public int Count { get; set; }

        [InverseProperty("UniversityPage")]
        public virtual ICollection<University> University { get; set; }
    }
}