// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UniversitiesAPI.Infrastructure.Contracts.DBEntities
{
    public partial class University
    {
        public University()
        {
            UniversityDomain = new HashSet<UniversityDomain>();
            UniversityWebPage = new HashSet<UniversityWebPage>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string AlphaTwoCode { get; set; }
        public string StateProvince { get; set; }
        [Required]
        public string Country { get; set; }
        public bool Deleted { get; set; }
        public int UniversityPageId { get; set; }

        [ForeignKey("UniversityPageId")]
        [InverseProperty("University")]
        public virtual UniversityPage UniversityPage { get; set; }
        [InverseProperty("University")]
        public virtual ICollection<UniversityDomain> UniversityDomain { get; set; }
        [InverseProperty("University")]
        public virtual ICollection<UniversityWebPage> UniversityWebPage { get; set; }
    }
}