// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace StarWarsAPITest.Infrastructure.Contracts.DBEntities
{
    public partial class DB_PlanetEntity
    {
        [Key]
        public int Id { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        [StringLength(100)]
        public string RotationPeriod { get; set; }
        [StringLength(100)]
        public string OrbitalPeriod { get; set; }
        [StringLength(100)]
        public string Climate { get; set; }
        [StringLength(100)]
        public string Population { get; set; }
        [StringLength(100)]
        public string Url { get; set; }
    }
}