// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BankAccountOOPMultiuser.Infrastructure.Contracts.Entities
{
    [Table("Movement")]
    public partial class Movement

    {
        [Key]
        public int Id { get; set; }
        public int AccountId { get; set; }
        [Column(TypeName = "decimal(8, 2)")]
        public decimal Value { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }

        [ForeignKey("AccountId")]
        [InverseProperty("Movements")]
        public virtual AccountEntity Account { get; set; }
    }
}