// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using UniversitiesAPI.Infrastructure.Contracts.DBEntities;

namespace UniversitiesAPI.Infrastructure.Contracts.DBContext
{
    public partial class UniversityDBContext : DbContext
    {
        public UniversityDBContext()
        {
        }

        public UniversityDBContext(DbContextOptions<UniversityDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<University> University { get; set; }
        public virtual DbSet<UniversityDomain> UniversityDomain { get; set; }
        public virtual DbSet<UniversityPage> UniversityPage { get; set; }
        public virtual DbSet<UniversityWebPage> UniversityWebPage { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=P-0501\\SQLEXPRESS;Initial Catalog=UniversityDB;Persist Security Info=True;User ID=jesus;Password=navarro");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<University>(entity =>
            {
                entity.HasOne(d => d.UniversityPage)
                    .WithMany(p => p.University)
                    .HasForeignKey(d => d.UniversityPageId)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_UniversityPage_University");
            });

            modelBuilder.Entity<UniversityDomain>(entity =>
            {
                entity.HasOne(d => d.University)
                    .WithMany(p => p.UniversityDomain)
                    .HasForeignKey(d => d.UniversityId)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_University_UniversityDomain");
            });

            modelBuilder.Entity<UniversityWebPage>(entity =>
            {
                entity.HasOne(d => d.University)
                    .WithMany(p => p.UniversityWebPage)
                    .HasForeignKey(d => d.UniversityId)
                    .OnDelete(DeleteBehavior.Cascade)
                    .HasConstraintName("FK_University_UniversityWebPage");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}